package com.example.demo.constcomponent.messengerEnums.payloads;

public enum Payloads {
	GET_STARTED_PAYLOAD,
	MENU_PAYLOAD,
	FILLING_MENU_PAYLOAD,
	CREATE_OWN_CROISSANT_PAYLOAD,
	DELETE_BUTTON_PAYLOAD,
	OWN_CROISSANT_MENU_PAYLOAD,
	ORDER_PAYLOAD,
	SHOW_MORE_PAYLOAD,
	FOR_GETTING_MENU,
	GET_ORDER,
	COMPLETE_ORDER,
	NAVIGATION_MENU,

}
