package com.example.demo.constantEnum.messengerEnums;

public enum Cases {
    ADD,MENU, ADD_FILLING,
    FILLING_MENU,
    ORDERING,
    COURIER_REQUEST,
    COURIER_ACTIONS,
    GET_LIST_OF_ORDERING,
    COMPLETING_ORDERINGS,
    CREATE_OWN_CROISSANT,
    CUSTOMER_REGISTER,
    PERSONAL_REQUEST,
    ADMIN_REQUEST,
    COURIER_REGISTRATION,
    COURIER_REGISTRATION_FINAL,
    ORDERING_LIST_FILLING,
    COMPLETE_ORDERINGS_LIST,
    COMPLETE_CROISSANT_SECOND_STEP,
    CUSTOMER_REGISTER_FINALIZE,
    ABORT,
    LANGUAGE_CHANGE,
    ASK_PHONE_NUMBER,
    ASK_ADDRESS,
    ASK_TIME,
    DELETE_ORDERINGS,
    NAVI,


}
