package com.example.demo.enums.telegramEnums;

public enum CallBackData {
    ORDERING_DATA,
    CROISSANT_TYPE_DATA,
    CROISSANT_TYPE_ADDING_DATA,
    MENU_DATA,
    CREATE_OWN_CROISSANT_DATA,
    DELETE_BUTTON_DATA,
    CREATE_OWN_QUESTION_DATA,
    ONE_MORE_ORDERING_DATA,
    SURE_TO_DELETE_DATA,
    SET_ROLE_DATA,
    SET_HELLO_MESSAGE_DATA,
    SETTING_ROLE_DATA_1,
    SETTING_ROLE_DATA_2,
    CANCEL_DATA,
    LIST_OF_ORDERING_DATA,
    COMPLETE_ORDERING_DATA,
    MAKE_ORDER_DATA
}
