package com.example.demo.enums.telegramEnums;

public enum TelegramUserStatus {
    ASKING_TYPE_STATUS,
    GETTING_MENU_STATUS,
    TEL_NUMBER_ORDERING_STATUS,
    FILLING_PHONE_NUMBER_STATUS,
    ADDRESS_STATUS,
    TIME_STATUS,
    OWN_MENU_STATUS,
    INPUTTING_FILLINGS_IN_OWN_CROISSANT_STATUS,
    ONE_MORE_ORDERING_STATUS,
    ONE_MORE_ORDERING_GETTING_MENU_STATUS,
    ADDING_FILLING_STATUS,
    ADDING_FILLING_STATUS_1,
    ADDING_CROISSANT_STATUS
}
