package com.bots.lvivCroissantBot.constantEnum.messengerEnums.payloads;

public enum QuickReplyPayloads {
    CROISSANT_TYPE_PAYLOAD,
    COURIER_QUESTION_PAYLOAD,
    ONE_MORE_ACTION_COURIER_PAYLOAD,
    ADDRESS_PAYLOAD,
    TYPE_PAYLOAD,
    ADMIN_REQUEST_PAYLOAD,
    PERSONAL_REQUEST_PAYLOAD,
    LANGUAGE_PAYLOAD,
    CREATING_OWN_CROISSANT_PAYLOAD,
    ONE_MORE_ORDERING,
    ACCEPT_ORDERING_PAYLOAD,
    GET_LIST_OF_ORDERING,
    COMPLETING_ORDERINGS,
    COURIER_REQ_ADMIN_SIDE_PAYLOAD,
    PAYMENT_WAY,
    QUESTION_APPROVING
}
