package com.bots.lvivcroissantbot.constantenum.telegram;

public enum TelegramUserStatus {
    ASKING_TYPE_STATUS,
    GETTING_MENU_STATUS,
    TEL_NUMBER_ORDERING_STATUS,
    FILLING_PHONE_NUMBER_STATUS,
    ADDRESS_STATUS,
    TIME_STATUS,
    OWN_MENU_STATUS,
    INPUTTING_FILLINGS_IN_OWN_CROISSANT_STATUS,
    ONE_MORE_ORDERING_STATUS,
    ONE_MORE_ORDERING_GETTING_MENU_STATUS,
    ADDING_FILLING_STATUS,
    ADDING_FILLING_STATUS_1,
    ADDING_CROISSANT_STATUS,
    ADDING_CROISSANT_STATUS_1,
    NULL_CHECKING_ADDING_CROISSANT_STATUS,
    NULL_CHECKING_ADDING_CROISSANT_STATUS_1,
    SETTING_ROLE_STATUS,
    SETTING_ADMIN_STATUS,
    SETTING_CUSTOMER_STATUS,
    SETTING_COURIER_STATUS,
    SETTING_PERSONAL_STATUS,
    NAME_OF_NEW_TEXT_STATUS,
    PHONE_ENTERING_IN_START_STATUS
}
